[colors]
background    = '#282828' # bg0
foreground    = '#d4be98' # fg0

selection_bg  = '#3c3836' # bg_current_word
selection_fg  = '#a89984' # grey2

cursor_fg     = '#3c3836' # bg_current_word
cursor_bg     = '#a89984' # grey2
cursor_border = '#a89984' # grey2

ansi = [
    '#282828', # bg0
    '#ea6962', # red
    '#a9b665', # green
    '#d8a657', # yellow
    '#7daea3', # blue
    '#d3869b', # purple
    '#89b482', # aqua
    '#d4be98', # fg0
]

brights = [
    '#7c6f64', # grey0
    '#ea6962', # red
    '#a9b665', # green
    '#d8a657', # yellow
    '#7daea3', # blue
    '#d3869b', # purple
    '#89b482', # aqua
    '#ddc7a1', # fg1
]

[colors.indexed]

[metadata]
name = 'gruvbox_material_dark_medium'
