#/bin/bash

# Setup our monitors
xrandr --output HDMI-A-0 --mode 1920x1080 --output DisplayPort-0 --mode 2560x1440 --right-of HDMI-A-0

# Apply our wallpaper
feh --bg-center ~/.repositories/nix-config/assets/chinatown.png

# Disable screen saver and DPMS features
xset s off -dpms

# Start our notification daemon
dunst &

# Enable our compositor
picom -b

# Fix for pinentry bug on NixOS
gpgconf --reload gpg-agent

# Launch our window manager
exec xmonad
