#/bin/bash

# Setup our monitors
xrandr --output HDMI-A-0 --mode 1920x1080 --output DisplayPort-0 --mode 2560x1440 --right-of HDMI-A-0

# Apply our wallpaper
feh --bg-center ~/Projects/dotfiles.nix/assets/chinatown.png

# Enable our compositor
picom -b

# Launch our window manager
exec xmonad
